#------------------------------------
# Control-M/Agent docker container
#------------------------------------

FROM centos

RUN yum update -y && yum install -y wget

RUN cd /etc/yum.repos.d && wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo

RUN yum install -y binutils qt gcc make patch libgomp glibc-headers glibc-devel kernel-headers kernel-devel dkms

RUN yum install -y VirtualBox-5.1

ADD workbench_ova-1.0.0-20170504.084926-37.ova /work

RUN vboxmanage import --vsys 0 --vmname wkb1 /work/workbench_ova-1.0.0-20170504.084926-37.ova

EXPOSE 8443:8443

WORKDIR /root

CMD vboxmanage startvm "wkb1" --type headless
